INSERT INTO DEPT (DEPT_ID, DEPT_NAME)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;

INSERT INTO DEPT
VALUES (NULL,'TT');


INSERT INTO DEPT
VALUES (20,'TT');

UPDATE DEPT
SET DEPT_NAME='TT'
WHERE DEPT_ID=20;

INSERT INTO DEPT (DEPT_ID, DEPT_NAME)
VALUES (10, 'Accounts');

INSERT INTO DEPT
VALUES ('A1','Accounts');

INSERT INTO DEPT
VALUES (30,'Accounts');

SELECT * FROM DEPT ORDER BY DEPT_ID;