<!ELEMENT catalog (product)>

<!ELEMENT product (catalog_item+)>
<!ATTLIST product
    description CDATA #REQUIRED
    product_image CDATA #REQUIRED
>

<!ELEMENT catalog_item (item_number, price, size+)>
<!ATTLIST catalog_item
    gender (Mens|Womens) #REQUIRED
>

<!ELEMENT item_number (#PCDATA)>

<!ELEMENT price (#PCDATA)>

<!ELEMENT size (color_swatch+)>
<!ATTLIST size
    description (Small|Medium|Large|ExtraLarge) #REQUIRED
>

<!ELEMENT color_swatch (#PCDATA)>
<!ATTLIST color_swatch
    image CDATA #REQUIRED
>