CREATE TABLE EMP (
    ID NUMBER(7),
    LAST_NAME VARCHAR2(25) NOT NULL,
    FIRST_NAME VARCHAR2(25),
    DEPT_ID NUMBER(7),

    CONSTRAINT EMP_PK PRIMARY KEY (ID),
    CONSTRAINT EMP_DEPT_FK
        FOREIGN KEY (DEPT_ID)
        REFERENCES DEPT(DEPT_ID)
);

DESC EMP;

INSERT INTO EMP
VALUES (101,'Sam','Sundar',10);

INSERT INTO EMP
VALUES (101,'Ram','Krishna',20);

INSERT INTO EMP
VALUES (102,'Gopi',NULL,40);


SELECT * FROM DEPT
ORDER BY DEPT_ID;

INSERT INTO DEPT
VALUES (40, 'Human Resources');

INSERT INTO EMP
VALUES (102, 'Gopi', NULL, 40);

INSERT INTO EMP
VALUES (103,NULL,'Ram',20);

SELECT * FROM EMP;
